AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/*.rake'
    - '**/config.ru'
  Exclude:
    - '**/Gemfile'
    - '**/log/**/*'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/public/**/*'
    - '**/config/**/*'
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/spec/rails_helper.rb'
    - '**/spec/spec_helper.rb'
    - '**/channels/application_cable/channel.rb'
    - '**/channels/application_cable/connection.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 25

ModuleFunction:
  Enabled: false

Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false


Style/ClassAndModuleChildren:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
# only force style on short strings... if they get a bit long, don't enforce
Style/IfUnlessModifier:
  MaxLineLength: 80
# unless can get confusing sometimes
Style/NegatedIf:
  Enabled: false
# It's not redundant, it's documentation
Style/RedundantReturn:
  Enabled: false
# I'd rather be explicit than accidentally reference a keyword or variable.
Style/RedundantSelf:
  Enabled: false
# Suggest using auto-cleanable resources (p.ex File.open with block)
Style/AutoResourceCleanup:
  Enabled: true
# Keep consistency in calls of Enumerable methods (p.ex inject vs reduce)
Style/CollectionMethods:
  Enabled: true
Style/MutableConstant:
  Enabled: true
Style/GuardClause:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Lint/LiteralInInterpolation:
  AutoCorrect: true
