default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:   <%= ENV["SI_PROJECT_DATABASE_USER"] %>
  password:   <%= ENV['SI_PROJECT_DATABASE_PASSWORD'] %>
  host:       <%= ENV['SI_PROJECT_DATABASE_HOST'] %>
  port:       <%= ENV['SI_PROJECT_DATABASE_PORT'] || "5432" %>
  url:        <%= ENV['SI_PROJECT_DATABASE_URL'] %>


development:
  <<: *default
  database: si-project_development

test:
  <<: *default
  database: si-project_test

staging:
  <<: *default
  database: si-project_staging

production:
  <<: *default
  database: si-project_production
